---

- name: restart all pleroma instances
  become: yes
  command: "systemctl restart pleroma@*.service"

- name: restart pleroma instance
  become: yes
  systemd: name="pleroma@{{pleroma_instance}}.service" state="restarted" daemon_reload="yes"
